### ISSUE TITLE
Game Arcade - make over

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/toolsDocs#17]
### context
Pedro Wibo :
>hello nico! quoi de beau ? si ca te dit on refait un événement jeu vidéo au labo. je voulais savoir si c’était possible de t’emprunter la borne d’arcade. merci bon week-end !

PH avait déjà emprunté l'arcade l'année dernière, elle n'a pas changé d'un poil depuis et @Jorgininho a débugé le RPI qui bootait plus, et updaté le système de la version 4.x à la 18.x, il était temps.
Du coup, ok, ça fait 2 ans que j'ai plus rien bricolé à par les book comptables. So fuck it. Let's make over this arcade. 
### objectif
C'est une bonne occasion de pratiquer avec Julien la méthodo de documentation github, ajouter une fonction bouton pour activer un script de shutdown, recabler les commandes, ajouter des upgrades hardware et software (trier les jeux les mieux) et finaliser une surcouche de swag. 

Évidemment, la deadLine est ce week-end pour leur événement. 
On doit se fixer des milestones avec MVP et options suivant le tps qu'on a et les surprises rencontrées.

### PROCESS
Pour tout ceci, j'aimerai utiliser github mais en utilisant soit projet, soit zenhub.... pour la création des todolist et milestones. 

- [x] start an issue
- [x] assign leader
- [x] collect whishlist of upgrade
- [ ] organize milestone in MVP1,2,3
- [x] Todolist with assignees
- [x] document in issues
- [ ] report at each milestone = branch, summary.md and PR
- [ ] do we have time to go for next milestone? Y/N

**Comment by nicolasdb** [comment]
# state of now.
![image](https://user-images.githubusercontent.com/12049360/50767774-6ae3bd00-127e-11e9-8915-d829ec443019.png)

## cover pour HP
![image](https://user-images.githubusercontent.com/12049360/50767812-9070c680-127e-11e9-80ed-74e0ca63b37c.png)

## Electronic wiring
![image](https://user-images.githubusercontent.com/12049360/50767836-a54d5a00-127e-11e9-8323-92d62a4d88e9.png)

## Named control and clean shutdown in the middle 
![image](https://user-images.githubusercontent.com/12049360/50767845-b5653980-127e-11e9-908c-cbbd2bd3a593.png)

## Sides and Swag
![image](https://user-images.githubusercontent.com/12049360/50767902-d62d8f00-127e-11e9-85f8-bb2d0ac12713.png)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/51034601-92e95e00-15a7-11e9-8bc8-ab67590f67e8.png)

**Comment by nicolasdb** [comment]
Total découpe laser pour le side et coverHP 4h. 

Bilan, 
La livraison est cet aprem, pil dans les tps. 
1 semaine pour design, gravures et découpes, ajustement, ponçage et vernir. 
+ côté electronique. 
Mise à jour recalBox, ajout script bouton shutdown, verification des cables et boutons, mod de l'electronique audio. 

D'un point de vue workshop ou production d'une personnalisation, il y a bcp à optimiser pour gagner du tps. 
Si l'arcade est inconnue et qu'on s'occupe des designs, il faut 1 semaine. 5x450 = 2250€, en incluant le tps machine. +BO + vernis = 2500€ htva
Si l'arcade est connue, qu'on a les plans et les designs. C'est 2 jours. Si désassembler est possible.

**Comment by nicolasdb** [comment]
![bartopv2](https://user-images.githubusercontent.com/12049360/51187850-01e2f180-18dd-11e9-9f76-1d9df48cb3f6.gif)

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/51196182-e254c480-18ee-11e9-87b8-510b0a9e4e89.png)

A final nice super overthetop last touch. An overlay/distortion CRT like. 
https://www.reddit.com/r/Unity2D/comments/4xrca8/trying_to_recreate_an_old_crt_feeling_monitor/

But way over what I can do myself .... ^^

**Comment by nicolasdb** [comment]
ha ben cette issue est close depuis longtps. 
https://nicolasdb.github.io/post/arcadeBarTop/
